# Generated by Django 4.2.6 on 2023-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_basket_size_basket_total_product_oldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discountCategory',
            field=models.CharField(default='null', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='isOffer',
            field=models.BooleanField(default=0),
        ),
    ]
